filter:
    paths:
        - Src/*
filter:
    excluded_paths:
        - Doc/*
        - vendor/*
build:
    environment:
        php:
            version: 5.5
    dependencies:
        before:
            - mysql -uroot -e "create database IF NOT EXISTS kabar_tests;"
            - mysql -uroot -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
            - mysql -uroot -e "GRANT ALL ON kabar_tests TO 'root'@'localhost';"
    tests:
        override:
            - ./bin/run-unit-tests.sh