filter:
    paths:
        - Src/*
filter:
    excluded_paths:
        - Doc/*
        - vendor/*
build:
    environment:
        php:
            version: 5.5
    dependencies:
        before:
            - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS kabar_tests;"
            - mysql -uroot -e "CREATE USER 'kabar'@'localhost' IDENTIFIED BY 'kabar';"
            - mysql -uroot -e "GRANT ALL ON kabar_tests.* TO 'kabar'@'localhost';"
    tests:
        override:
            - ./bin/run-unit-tests.sh