# Run after dependencies
project_setup:
    before:
        - sudo service start mysql || true
        - mysql -e "CREATE DATABASE abc"
filter:
    paths:
        - Src/*
filter:
    excluded_paths:
        - Doc/*
        - vendor/*
build:
    environment:
        php:
            version: 5.5
    tests:
        override:
            - ./bin/run-unit-tests.sh